<div class="page-header">
    <h3>
        Edición de Seciones.
        <small><?php eh(strtoupper($seccion->nombres))?></small>
    </h3>
</div>
<div class="row">
    <div class="span3">
        <?php //View::partial('backend/menus/usuarios') ?>
    </div>
    <div class="span8 span-derecho">
        <div id="res-form-ajax"><?php View::content() ?></div>
        <?php echo Ajax::form('res-form-ajax', NULL, 'form-horizontal') ?>
        <?php echo Form::hidden('seccion.id') ?>
        <?php echo Form::label('Nombre: ', 'nombre') ?>
        <?php echo Form::text('seccion.nombre','size="100"',NULL) ?>

        <div class="form-actions">
            <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
            <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
        </div>
        <?php echo Form::close() ?>
    </div>
</div>