<div class="page-header">
    <h3>Contratos</h3>
    <?echo Html::link("admin/nuevocontrato","Nuevo contrato","class='btn btn-primary'")?>
</div>
<div class="span10">
    <table class="table table-bordered table-striped">
        <thead><tr style="text-align:center;font-weight:bold;">
                <th>NUMERO</th>
                <th>OBJETO</th>
                <th>VALOR INICIAL</th>
                <th>FECHA INICIO</th>
                <th>FECHA FINAL</th>
                <th>PUNTAJE</th>
                <th>PROVEEDOR</th>
                <th>ACCIONES</th>
            </tr></thead>   

        <tbody>
            <? foreach ($contratos as $obj) { ?>
                <tr>
                    <td><? echo $obj->numero ?></td>
                    <td><? echo $obj->objeto ?></td>
                    <td><? echo $obj->valorini ?></td>
                    <td><? echo $obj->fechaini ?></td>
                    <td><? echo $obj->fechafinal ?></td>
                    <td><? echo $obj->puntaje ?></td>
                    <td><? echo $obj->proveedor_id ?></td>
                    <td><? echo Html::linkAction("modificar/$obj->id", "MOD") ?></td>
                    <td>
                        <? echo Html::linkAction("eliminar/$obj->id", "Eliminar") ?>
                    </td>
                </tr>
            <? } ?> 
        </tbody>
    </table> 
</div>