<div><? echo View::content() ?></div>
<legend>¿Está seguro de eliminar este Contrato?</legend>
<? echo Form::open() ?>
<div class="page-header">    
    <? echo Form::submit("Eliminar","class='btn btn-primary'")?>
    <?echo Html::linkAction("contratos", "Cancelar","class='btn btn-primary'")?>
    <? echo Form::hidden("idcontrato", null, "$objContrato->id")?>
</div>

<div> <? echo Form::label("Numero del contrato", "contratos.numero") ?>
    <? echo Form::text("contratos.numero", "class='input-large' placeholder='Numero del contrato'", "$objContrato->numero") ?></div>

<div> <? echo Form::label("Objeto del contrato", "contratos.objeto") ?>
    <? echo Form::text("contratos.objeto", "class='input-large' placeholder='Objeto del contrato'", "$objContrato->objeto") ?></div>

<div> <? echo Form::label("Valor inicial", "contratos.valorini") ?>
    <? echo Form::text("contratos.valorini", "class='input-large' placeholder='Valor inicial'", "$objContrato->valorini") ?></div>

<div> <? echo Form::label("Fecha de suscripción", "contratos.fechaini") ?>
    <? echo Form::date("contratos.fechaini", null,null, "$objContrato->fechaini") ?></div>

<div> <? echo Form::label("Fecha de terminación", "contratos.fechafin") ?>
    <? echo Form::date("contratos.fechafinal", null, null, "$objContrato->fechafinal") ?></div>

<div> <? echo Form::label("Puntaje", "contratos.puntaje") ?>
    <? echo Form::text("contratos.puntaje", "class='input-large' placeholder='Puntaje'", "$objContrato->puntaje") ?></div>

<div> <? echo Form::label("Proveedor", "contratos.proveedor_id") ?>
    <? echo Form::text("contratos.proveedores_id", "class='input-large' placeholder='Proveedor'", "$objContrato->proveedores_id") ?></div>

<?php echo Form::close(); ?>