<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<legend>Evaluación del Proveedor : <?php echo $proveedor->nombres . " " . $proveedor->apellidos ?></legend>
<legend>Identificación : <?php echo $proveedor->identificacion ?></legend>
<div class="well" style="padding: 8px;border-radius: 2px;">
    <?php Form::open() ?>
    <? echo Html::link("admin/nuevocontrato/$proveedor->id", "Nuevo contrato", "class='btn btn-primary'") ?>    
    <?php Form::close() ?>
</div>

<?php
$dt = new DataTable($contratos);
$dt->addFields('id', 'numero', 'objeto', 'valorini', 'fechaini', 'fechafinal', 'puntaje','puntaje * valorini');
$dt->addHeaders('id', 'Código', 'Objeto', 'Valor inicial', 'Fecha inicial', 'Fecha final', 'Puntaje', 'Pon Parcial', 'Editar', 'Eliminar');
$dt->imgLink('figuras/editar.png', 'admin/editarcontrato');
$dt->imgLinkConfirm('figuras/eliminar.png', 'admin/eliminarcontrato', '', '¿Está seguro?');
echo $dt->render('class="table table-bordered table-striped"');
?>

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span10">
            <table class="table table-bordered table-striped">
                <thead><tr style="text-align:center;font-weight:bold;">
                        <th>CONTRATO</th>
                        <th>VALOR INICIAL</th>
                        <th>F. SUSCRIPCIÓN</th>
                        <th>F. TERMINACION</th>
                        <th>PUN. OBTENIDO</th>
                        <th>PON. PARCIAL</th>
                    </tr></thead>   

                <tbody>
                    <?php $valores = 0;
                    $parciales = 0;
                    ?>
<? foreach ($contratos2 as $obj) { ?>
                        <tr>
                            <td><? echo $obj->numero ?></td>
                            <td><? echo $obj->valorini ?></td>
                            <td><? echo $obj->fechaini ?></td>
                            <td><? echo $obj->fechafinal ?></td>
                            <td><? echo $obj->puntaje ?></td>
                            <td><? echo $obj->valorini * $obj->puntaje ?></td>
                        </tr>
                        <?
                        $valores += $obj->valorini;
                        $parciales +=($obj->valorini * $obj->puntaje);
                    }
                    ?> 
                </tbody>
                <tr style="color: blue">
                    <td>SUM CONTRATOS</td>
                    <td><?php echo $valores ?></td>
                    <td></td>
                    <td></td>
                    <td>SUM PARCIALES</td>
                    <td><?php echo $parciales ?></td>
                </tr>
                <tr style="color: #408140">
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>PON TOTAL</td>
                    <td><?php
                    if ($valores >0){
                        echo round($parciales / $valores ,2);
                    }                    
                    ?>
                    </td>
                </tr>
            </table> 
        </div>
    </div>
</div>

