<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<legend>Evaluación del Proveedor : <?php echo $proveedor->nombres . " " . $proveedor->apellidos ?></legend>
<legend>Identificación : <?php echo $proveedor->identificacion ?></legend>
<div class="well" style="padding: 8px;border-radius: 2px;">
    <?php Form::open() ?>
    <? echo Html::link("admin/nuevocontrato/$proveedor->id", "Nuevo contrato", "class='btn btn-primary'") ?>    
    <? echo Html::link("admin/repExContratoProv/$proveedor->id", "Exportar a Excel", "class='btn btn-primary'") ?>    
    <?php Form::close() ?>
</div>

<?php
$dt = new DataTable($contratos);
$dt->addFields('id', 'numero', 'objeto', 'valorini', 'fechaini', 'fechafinal', 'puntaje', 'value');
$dt->addHeaders('id', 'Numero', 'Objeto', 'Valor inicial', 'Fecha inicial', 'Fecha final', 'Puntaje', 'Pon Parcial', 'Editar', 'Eliminar');
$dt->imgLink('figuras/editar.png', 'admin/editarcontrato');
$dt->imgLinkConfirm('figuras/eliminar.png', 'admin/eliminarcontrato', '', '¿Está seguro?');
echo $dt->render('class="table table-bordered table-striped"');
?>

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span10">
            <table class="table table-bordered table-striped">
                <thead style="width: 100%"><tr style="text-align:center;font-weight:bold;">
                        <th style="width: 33%">SUMATORIA VALORES CONTRATO</th>
                        <th style="width: 33%">SUMATORIA PARCIALES</th>
                        <th style="width: 33%">PONDERADO TOTAL</th>
                    </tr></thead>   

                    <?php
                    $valores = 0;
                    $parciales = 0;
                    ?>
                    <? foreach ($contratos2 as $obj) { ?>
                        <? $obj->numero ?>
                        <? $obj->valorini ?>
                        <? $obj->fechaini ?>
                        <? $obj->fechafinal ?>
                        <? $obj->puntaje ?>
                        <? $obj->valorini * $obj->puntaje ?>
                        <?
                        $valores += $obj->valorini;
                        $parciales +=($obj->valorini * $obj->puntaje);
                    }
                    ?>
                <tr style="color: blue">
                    <td><?php echo $valores ?></td>
                    <td><?php echo $parciales ?></td>
                    <td><?php
                    if ($valores > 0) {
                        echo round($parciales / $valores, 2);
                    }
                    ?>
                    </td>
                </tr>
            </table> 
        </div>
    </div>
</div>

