<legend>Proveedores Registrados.</legend>

<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<div class="well" style="padding: 8px;border-radius: 2px;">
    <? echo Html::link("admin/nuevoproveedor", "Nuevo proveedor", "class='btn btn-primary'") ?>
</div>
<div>
    <? echo Form::open("admin/proveedores", "POST", "class='form-inline'") ?>
    Buscar por: 

    <?
    $comboBusqueda = array('IDENTIFICACION', 'APELLIDO');

    echo Form::select("comboBusqueda", $comboBusqueda, "IDENTIFICACION");
    echo Form::text("textoBusqueda", "class='input-medium search-query'");
    echo Form::submit("Buscar", "class='btn btn-danger'")
    ?>
    <? echo Form::close() ?>
</div>
<?php
$dt = new DataTable($proveedores);
$dt->addHeaders('id', 'Identificacion', 'Nombre / Razon Social','Nombres', 'Apellidos' ,'Direccion', 'Celular', 'Editar', 'Actividades','Contratos','Eliminar');
$dt->addFields('id', 'identificacion', 'razonsocial', 'nombres', 'apellidos', 'direccion', 'celular');
$dt->imgLink('figuras/editar.png', 'admin/editarproveedor');
$dt->imgLink('figuras/actividades.png', 'admin/actividades');
$dt->imgLink('figuras/contrato.png', 'admin/ponderacion');
$dt->imgLinkConfirm('figuras/eliminar.png', 'admin/eliminarproveedor', '', '¿Realmente desea Eliminar Este Proveedor?'); 
echo $dt->render('class="table table-bordered table-striped"');
?>