<legend>Proveedores Registrados.</legend>

<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<div class="well" style="padding: 8px;border-radius: 2px;">
    <? echo Html::link("admin/nuevoproveedor", "Nuevo proveedor", "class='btn btn-primary'") ?>

</div>
<div class="well" style="padding: 8px;border-radius: 2px;">
    <? echo Form::open("admin/proveedores", "POST", "class='form-inline'") ?>
    Buscar por: 

    <?
    $comboBusqueda = array('IDENTIFICACION', 'APELLIDO', 'NOMBRE/RAZON SOCIAL');

    echo Form::select("comboBusqueda", $comboBusqueda, "IDENTIFICACION");
    echo Form::text("textoBusqueda", "class='input-medium search-query'");
    echo Form::submit("Buscar", "class='btn btn-danger'");
    ?>
    <? echo Html::link("admin/proveedores", "Mostrar todos", "class='btn btn-success'") ?>
    <? echo Form::close() ?>
</div >
<div class="well" style="padding: 8px;border-radius: 2px;">
    <? echo Form::open("admin/proveedores", "POST", null) ?>
    <table>
        <tr>
            <td>
                Sección:
                <div id="div_seccion">
                    <? echo Form::dbSelect('seccion.seccion_id', 'nombre'); ?>
                </div>
            </td>
            <td>
                División:
                <div id='div_division'>

                    <select id="division_division_id" name="division_division_id"><option value="">Seleccione</option></select>
                </div> 
            </td>
            <td>
                Actividad:
                <div id='div_actividad'>
                    <select id="actividad_actividad_id" name="actividad_actividad_id"><option value="">Seleccione</option></select>
                </div>
            </td>
            <td>
                <? echo Form::submit("Buscar", "class='btn btn-danger'") ?>
            </td>

            <? echo Form::close() ?>
        </tr>
    </table>
</div>
<? echo Form::open("admin/guardartemp") ?>
<div class="well" style="padding: 8px;border-radius: 2px;">
    <?
    //echo Form::label("Tipo de reporte:","comboBusqueda");
    //$comboBusqueda = array('CVS', 'PDF');
    //echo Form::select("comboBusqueda", $comboBusqueda, "CVS");
    ?>
    <? echo Form::submit("Guardar temporal", "class='btn btn-info'") ?>
    <? echo Html::link("admin/borrartemp", "Borrar temporal","class='btn btn-info'")?>
    <? echo Html::link("admin/reportepdf1", "Enviar a excel (temporal)","class='btn btn-info'")?>
    <? echo Html::link("admin/reportepdftodos", "Enviar a excel (todos)","class='btn btn-info'")?>
    <? echo Html::link("admin/reportecontratostemp", "Reporte contratos (temporal)","class='btn btn-info'")?>
    <? echo Html::link("admin/reportecontratotodos", "Reporte contratos (todos)","class='btn btn-info'")?>
</div>
<?php
$dt = new DataTable($proveedores);
$dt->addHeaders('id', 'Identificacion', 'Nombre / Razon Social', 'Nombres', 'Apellidos', 'Celular','Seleccionar', 'Editar', 'Actividades', 'Contratos', 'Imprimir','Rep.Datos','Eliminar');
$dt->addFields('id', 'identificacion', 'razonsocial', 'nombres', 'apellidos',  'celular');
$dt->check('id',null,1);

$dt->imgLink('figuras/editar.png', 'admin/editarproveedor');
$dt->imgLink('figuras/actividades.png', 'admin/actividades');
$dt->imgLink('figuras/contract.png', 'admin/ponderacion');
$dt->imgLink('figuras/contrato.png', 'admin/repExProv');
$dt->imgLink('figuras/contrato.png', 'admin/repExProvVertical');
$dt->imgLinkConfirm('figuras/eliminar.png', 'admin/eliminarproveedor', '', '¿Realmente desea Eliminar Este Proveedor?');
echo $dt->render('class="table table-bordered table-striped"');
?>

<? echo Form::close() ?>

<script type='text/javascript'>
    $("#seccion_seccion_id").change(function(){
        var seccion_id = $('#seccion_seccion_id').val();
        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'asistente/getDivisiones/'; ?>",
            data: "seccion_id=" + seccion_id,
            success: function(html){
                $("#div_division").html(html);
                
                
            }
        });
    });
</script>