<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar pull-right" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand">Empopasto</a>
            <div class="nav-collapse">
                <ul class="nav pull-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" style="text-transform: capitalize;">
                            Administrador
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><?php echo Html::link('admin/index/logout', 'Salir') ?></li>
                        </ul>
                    </li>
                </ul>
            </div>

            <div class="nav-collapse">
                <ul class="nav">
                    <li class="active"><a href="#">Inicio</a></li>
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">Proveedores <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><? echo Html::link("proveedores/nuevo", "Nuevo") ?></li>
                            <li><? echo Html::link("proveedores/index", "Listar") ?></li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">Actividades DIAN <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><? echo Html::link("seccion/index", "Secciones") ?></li>
                            <li><? echo Html::link("division/index", "Divisiones") ?></li>
                            <li><? echo Html::link("actividad/index", "Actividades") ?></li>
                            <li class="divider"></li>
                            <li class="nav-header">link cerrado</li>
                            <li><a href="#">Link separado</a></li>
                            <li>
                                <a href="#">Dos niveles <i class="icon-arrow-right"></i></a>
                                <ul class="dropdown-menu sub-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li class="divider"></li>
                                    <li class="nav-header">Nav header</li>
                                    <li><a href="#">Separated link</a></li>
                                    <li><a href="#">One more separated link</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>

                </ul>
            </div><!-- /.nav-collapse -->

        </div>
    </div>
</div>