<div id='cabecera' class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar pull-right" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <?php echo Html::link('', 'App KumbiaPHP', 'class="brand"') ?>
            <div class="nav-collapse">   
                <ul class="nav pull-right">
                    <li class="nav pull-right"><?php echo Html::link('admin/usuarios', 'Administración', 'class="dropdown-toggle" data-toggle="dropdown" ') ?></li>
                </ul>                
            </div>
        </div>
    </div>
</div>