<div class="page-header">
    <h3>
        Edición del Usuario
        <small><?php eh(strtoupper($proveedor->nombres . " " . $proveedor->apellidos))?></small>
    </h3>
</div>
<div class="row">
    <div class="span3">
        <?php //View::partial('backend/menus/usuarios') ?>
    </div>
    <div class="span8 span-derecho">
        <div id="res-form-ajax"><?php View::content() ?></div>
        <?php echo Ajax::form('res-form-ajax', NULL, 'form-horizontal') ?>
        <?php echo Form::hidden('proveedor.id') ?>
        <?php echo Form::text('proveedor.identificacion') ?>
        <?php echo Form::dbSelect('proveedores.tipo_identificacion_id',NULL,NULL,NULL,NULL,'proveedor.tipo_identificacion_id'); ?><!-- modelo . campo relacionado -->
        
        <?php echo Form::text('proveedor.nombres') ?>
        <?php echo Form::text('proveedor.apellidos') ?>

        <div class="form-actions">
            <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
            <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
        </div>
        <?php echo Form::close() ?>
    </div>
</div>