<legend>Proveedores Registrados.</legend>

<div id="mensajes_flash" >        
    <?php View::content() ?>
</div> 
<?php
View::partial('backend/barra_superior_listas', FALSE, array('texto' => 'Crear Usuario', 'opciones' => FALSE));
$dt = new DataTable($proveedores);
$dt->addHeaders('id', 'Identificacion', 'Nombre Completo', 'Editar');
$dt->addFields('id', 'identificacion', 'nombcomp');
$dt->imgLink('figuras/editar.png', 'admin/usuarios/editar');
echo $dt->render('class="table table-bordered table-striped"');
?>