
    <div><?php echo View::content()?></div>
    <?php echo Form::open() ?>
    <table>
        <tr><td style="width: 90%"><legend>Agregar Proveedor</legend>
    </td><td style="width: 10%"><?php echo Form::submit("Agregar","class='btn btn-primary'")?></td></tr>
</table>

<div class="tabbable"> 
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab1" data-toggle="tab">Datos personales</a></li>
        <li><a href="#tab2" data-toggle="tab">Otros Datos</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="tab1">
            <div> <?php echo Form::text("proveedores.identificacion", "class='input-large' placeholder='Identificaciòn persona'") ?></div>
            <div> <?php echo Form::text("proveedores.tipood", "class='input-large' placeholder='Tipo Identificaciòn'") ?></div>
            <div> <?php echo Form::text("proveedores.nombres", "class='input-large' placeholder='Nombres'") ?></div>
            <div> <?php echo Form::text("proveedores.apellidos", "class='input-large' placeholder='Pellidos'") ?></div>
        </div>
        <div class="tab-pane" id="tab2">
            <div> <?php echo Form::text("proveedores.rut", "class='input-large' placeholder='Rut'") ?></div>
        </div>
    </div>
</div>
<?php echo Form::close() ?>