<div><?php echo View::content() ?></div>
<?php echo Form::open() ?>
<table>
    <tr><td style="width: 90%"><legend>Agregar Proveedor</legend>
</td><td style="width: 10%"><?php echo Form::submit("Agregar", "class='btn btn-primary'") ?></td></tr>
</table>

<div class="tabbable"> 
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab1" data-toggle="tab">Datos personales</a></li>
        <li><a href="#tab2" data-toggle="tab">Actividades economicas</a></li>
        <li><a href="#tab3" data-toggle="tab">Seguridad</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="tab1">
            Tipo identificación: <? echo Form::dbSelect('proveedores.tipo_identificacion_id', 'nombre'); ?><!-- modelo . campo relacionado -->
            <div> <?php echo Form::text('proveedores.identificacion', 'class="input-large" placeholder="Identificación persona" title="Se necesita una identificación" required') ?></div>
            <div> <?php echo Form::text('proveedores.razonsocial', 'class="input-large" placeholder="Nombre o razón social" title="Se necesita el nombre o razón social" required') ?></div>
            Ciudad: <? echo Form::dbSelect('proveedores.ciudad_id', 'nombre'); ?><!-- modelo . campo relacionado -->
            <div> <?php echo Form::text('proveedores.nombres', 'class="input-large" placeholder="Nombres" title="Se necesitan los nombres" required') ?></div>
            <div> <?php echo Form::text('proveedores.apellidos', 'class="input-large" placeholder="Apellidos" title="Se necesitan los apellidos" required') ?></div>
            <div> <?php echo Form::text('proveedores.direccion', 'class="input-large" placeholder="Dirección"') ?></div>
            <div> <?php echo Form::text('proveedores.celular', 'class="input-large" placeholder="Celular"') ?></div>
            <div> <?php echo Form::text('proveedores.email', 'class="input-large" placeholder="Email"') ?></div>
            <div> <?php echo Form::text('proveedores.telefono', 'class="input-large" placeholder="Telefono fijo"') ?></div>
            <div> <?php echo Form::text('proveedores.fax', 'class="input-large" placeholder="Fax"') ?></div>
            <div> <?php echo Form::text('proveedores.profesion', 'class="input-large" placeholder="Profesión"') ?></div>
            Tipo proveedor: <? echo Form::dbSelect('proveedores.tipo_proveedor_id', 'nombre'); ?><!-- modelo . campo relacionado -->
            <div> <?php echo Form::text('proveedores.rut', 'class="input-large" placeholder="Rut"') ?></div>
            <div>Formación Académica persona natural.</div>
            <div><?php echo Form::textarea("proveedores.educaion", "class='input-xlarge' placeholder='Escriba aquí'") ?></div>
            Tipo entidad: <? echo Form::dbSelect('proveedores.tipo_entidad_id', 'nombre'); ?><!-- modelo . campo relacionado -->
            <div>Fecha de Matrícula Camara de Comercio: <?php echo Form::date('proveedores.camcomfecini', 'class="input-large" placeholder="Día/Mes/Año"') ?></div>
            <div>Fecha de Vencimiento Camara de Comercio: <?php echo Form::date('proveedores.camcomfecfin', 'class="input-large" placeholder="Día/Mes/Año"') ?></div>
        </div>
        <div class="tab-pane" id="tab2">
            <div> <?php echo Form::text('proveedores.rut', 'class="input-large" placeholder="Rut"') ?></div>
        </div>
        <div class="tab-pane" id="tab3">
            <div> <?php echo Form::pass('proveedores.contrasena', 'class="input-large" placeholder="Contraseña" required' . ' onchange="form.pwd2.pattern = this.value;"') ?></div>
            <div> <?php echo Form::pass('pwd2', 'class="input-large" placeholder="Repetir contraseña" required') ?></div>
        </div>
    </div>
</div>
<?php echo Form::close() ?>