<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar pull-right" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand">Empopasto</a>

            <div class="nav-collapse">
                <ul class="nav">
                    <li class="active"><a href="/empopasto_proveedores/">Inicio</a></li>
                    <li class="dropdown">
                        <? echo Html::link("registro/nuevonormal", "Registrame") ?>
                    </li>
                    <li class="dropdown">
                        <? echo Html::link("proveedores/index", "Ingresar") ?>
                    </li>
                </ul>
            </div><!-- /.nav-collapse -->

        </div>
    </div>
</div>